import express from "express";
import fetch from "node-fetch";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

/* ===========================
   HEALTH CHECK
=========================== */
app.get("/", (req, res) => {
  res.json({ status: "Specter Corp backend is running 🚀" });
});

/* ===========================
   PROMPT GENERATOR
=========================== */
app.post("/api/generate-prompt", async (req, res) => {
  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: "Prompt is required" });
  }

  // MOCK RESPONSE (replace with OpenAI later)
  res.json({
    result: `🔥 Enhanced Specter Prompt:\n\n${prompt}\n\n— Optimized for maximum impact.`
  });
});

/* ===========================
   SCRIPT GENERATOR
=========================== */
app.post("/api/generate-script", async (req, res) => {
  const { idea } = req.body;

  if (!idea) {
    return res.status(400).json({ error: "Idea is required" });
  }

  res.json({
    script: `🎬 Script Generated by Specter Corp\n\nTitle: ${idea}\n\n[Opening Scene]\nThe story begins with intensity and purpose...`
  });
});

/* ===========================
   KLING AI – PROMPT TO VIDEO
=========================== */
app.post("/api/kling-video", async (req, res) => {
  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: "Prompt is required" });
  }

  // ⚠️ PLACEHOLDER (Real Kling API goes here)
  // const response = await fetch("https://api.klingai.com/v1/video", {
  //   method: "POST",
  //   headers: {
  //     "Authorization": `Bearer ${process.env.KLING_API_KEY}`,
  //     "Content-Type": "application/json"
  //   },
  //   body: JSON.stringify({ prompt })
  // });

  res.json({
    video_url: "https://example.com/kling-video-placeholder.mp4",
    message: "Kling AI video generated (mock response)"
  });
});

/* ===========================
   ADMIN – VIEW PROMPTS
=========================== */
app.get("/api/admin/prompts", (req, res) => {
  res.json({
    admin: "Specter Corp Admin",
    prompts: [
      "AI horror movie prompt",
      "Motivational speech script",
      "Sci-fi short film idea"
    ]
  });
});

/* ===========================
   START SERVER
=========================== */
app.listen(PORT, () => {
  console.log(`🚀 Specter Corp backend running on port ${PORT}`);
});
